# Generated by Django 2.0.2 on 2018-10-21 23:52

import django.core.files.storage
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='captura',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='archivos/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='contenido',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
