# Generated by Django 2.1.3 on 2018-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181021_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='expediente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Expediente'),
        ),
    ]
