# Generated by Django 2.1.3 on 2018-11-28 19:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('core', '0003_auto_20181128_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='etiquetas',
        ),
        migrations.AddField(
            model_name='archivo',
            name='etiquetas',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
